-- Add extended user profile fields
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS first_name TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS last_name TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS city TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS country TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS additional_info TEXT NOT NULL,
  ADD COLUMN IF NOT EXISTS photo_url TEXT NOT NULL;
